# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV FLASK_APP=backend/app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Set the working directory in the container
WORKDIR /app/backend

# Create the uploads directory
RUN mkdir -p /app/backend/uploads

# Copy the requirements file into the container
COPY smartBP/backend/requirements.txt requirements.txt

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY smartBP/backend/ .

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["flask", "run"]
